[package]
name = "canistorage"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10.13"
ic-cdk = "0.17.1"
ic-cdk-timers = "0.11.0"
ic-stable-structures = "0.6.7"
ic-wasi-polyfill = "0.7.0"
